#!/usr/bin/env bash

case "$(printf "kill\nreboot\nshutdown" | dmenu -i -l 4)" in
	kill) ps -u "$USER" -o pid,comm,%cpu,%mem | dmenu -i -l 10 -p Kill: | awk '{print $1}' | xargs -r kill ;;
	reboot) loginctl reboot -i ;;
	shutdown) loginctl poweroff ;;
	*) exit 1 ;;
esac
